version: '3'

services:
  gerbil:
    image: gerbil
    container_name: gerbil
    command: ["./gerbil", "--config", "/config/gerbil.conf"]
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
    volumes:
      - ./config_example.json:/config/config.json
    restart: unless-stopped